function createSampleListings(ownerId) {
  return [
    {
      title: "Modern Apartment in Mumbai",
      description: "Beautiful stay with a skyline view, fast Wi-Fi, and easy access to cafes, shopping, and the metro.",
      price: 2500,
      location: "Mumbai",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-mumbai",
      },
      owner: ownerId,
    },
    {
      title: "Sea View Studio in Goa",
      description: "A bright coastal studio just steps from the beach with a breezy balcony and laid-back interiors.",
      price: 3200,
      location: "Goa",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-goa",
      },
      owner: ownerId,
    },
    {
      title: "Heritage Haveli in Jaipur",
      description: "Traditional Rajasthani details, a peaceful courtyard, and warm hospitality in the heart of the pink city.",
      price: 4100,
      location: "Jaipur",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-jaipur",
      },
      owner: ownerId,
    },
    {
      title: "Lakefront Cabin in Nainital",
      description: "Wake up to misty hills, calm lake views, and a cozy wooden interior perfect for a weekend escape.",
      price: 2900,
      location: "Nainital",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-nainital",
      },
      owner: ownerId,
    },
    {
      title: "Designer Loft in Bengaluru",
      description: "A stylish loft for work and leisure with modern decor, natural light, and a dedicated workspace.",
      price: 3600,
      location: "Bengaluru",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-bengaluru",
      },
      owner: ownerId,
    },
    {
      title: "Riverside Cottage in Rishikesh",
      description: "A peaceful cottage near the Ganga with mountain air, yoga spaces, and easy access to riverside cafes.",
      price: 2700,
      location: "Rishikesh",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-rishikesh",
      },
      owner: ownerId,
    },
    {
      title: "Luxury Villa in Udaipur",
      description: "Elegant rooms, lake views, and a private terrace make this villa ideal for a premium getaway.",
      price: 5800,
      location: "Udaipur",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-udaipur",
      },
      owner: ownerId,
    },
    {
      title: "Snow Cabin in Manali",
      description: "Cozy mountain living with pine views, warm wood interiors, and quick access to scenic trails.",
      price: 3400,
      location: "Manali",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-manali",
      },
      owner: ownerId,
    },
    {
      title: "French Quarter Flat in Pondicherry",
      description: "A colorful apartment with colonial charm, walkable streets, and cozy spots for slow mornings.",
      price: 3100,
      location: "Pondicherry",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-pondicherry",
      },
      owner: ownerId,
    },
    {
      title: "Hilltop Stay in Shimla",
      description: "A warm hillside retreat with forest views, vintage touches, and a fireplace for cold evenings.",
      price: 3300,
      location: "Shimla",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1464890100898-a385f744067f?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-shimla",
      },
      owner: ownerId,
    },
    {
      title: "Minimal Home in Delhi",
      description: "Clean design, central location, and all the essentials for a comfortable city stay near major attractions.",
      price: 2800,
      location: "Delhi",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-delhi",
      },
      owner: ownerId,
    },
    {
      title: "Tea Garden Retreat in Munnar",
      description: "Wake up above the tea estates in a calm retreat with cool weather, wide views, and quiet mornings.",
      price: 3500,
      location: "Munnar",
      country: "India",
      image: {
        url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-munnar",
      },
      owner: ownerId,
    },
    {
      title: "Clifftop Villa in Santorini",
      description: "A bright white villa with sea views, a private plunge pool, and unforgettable sunset evenings.",
      price: 9200,
      location: "Santorini",
      country: "Greece",
      image: {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-santorini",
      },
      owner: ownerId,
    },
    {
      title: "Canal Side Loft in Amsterdam",
      description: "A compact and stylish loft overlooking the canal, perfect for exploring museums and local cafes.",
      price: 6700,
      location: "Amsterdam",
      country: "Netherlands",
      image: {
        url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-amsterdam",
      },
      owner: ownerId,
    },
    {
      title: "Desert Escape in Dubai",
      description: "A sleek luxury stay with a rooftop pool, dramatic skyline views, and resort-style amenities.",
      price: 8600,
      location: "Dubai",
      country: "United Arab Emirates",
      image: {
        url: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1200&q=80",
        filename: "sample-dubai",
      },
      owner: ownerId,
    },
  ];
}

module.exports = createSampleListings;
